const defaults={focus:25,short:5,long:15,cycles:4,sound:true,autoStart:false};
const labels={focus:'Фокус',short:'Короткий отдых',long:'Длинный отдых'};
const codes={clock:'TIME / 01',stopwatch:'MEASURE / 02',pomodoro:'FOCUS / 03'};
const $=s=>document.querySelector(s), pad=n=>String(n).padStart(2,'0');
const valid=s=>s&&[s.focus,s.short,s.long].every(n=>Number.isInteger(n)&&n>=1&&n<=180)&&Number.isInteger(s.cycles)&&s.cycles>=1&&s.cycles<=12&&typeof s.sound==='boolean'&&typeof s.autoStart==='boolean';
let settings=defaults; try { const saved=JSON.parse(localStorage.getItem('6am-preferences')||localStorage.getItem('winter-arc-preferences')||'null'); if(valid(saved)) settings=saved; } catch {}
const duration=p=>settings[p]*60000, countdown=ms=>{const s=Math.max(0,Math.ceil(ms/1000));return `${pad(Math.floor(s/60))}:${pad(s%60)}`}, elapsed=(sw,now=Date.now())=>sw.accumulated+(sw.startedAt===null?0:Math.max(0,now-sw.startedAt)), elapsedText=ms=>{const s=Math.floor(Math.max(0,ms)/1000);return `${pad(Math.floor(s/3600))}:${pad(Math.floor(s/60)%60)}:${pad(s%60)}`};
const state={view:codes[location.hash.slice(1)]?location.hash.slice(1):'pomodoro',now:Date.now(),pomodoro:{phase:'focus',remaining:duration('focus'),deadline:null,completed:0,notice:''},stopwatch:{accumulated:0,startedAt:null,laps:[]}};
let audio=null;
let stopwatchFrame=0;
function updateStopwatch(){
  if(state.stopwatch.startedAt===null){stopwatchFrame=0;return}
  renderStopwatch();
  stopwatchFrame=requestAnimationFrame(updateStopwatch);
}
function startStopwatchFrame(){if(!stopwatchFrame)stopwatchFrame=requestAnimationFrame(updateStopwatch)}
function status(el,text,running){el.classList.toggle('running',running);el.innerHTML=`<i></i>${text}`}
function sound(){if(!settings.sound||!audio)return;[0,.25,.5].forEach(offset=>{const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=660;const start=audio.currentTime+offset;g.gain.setValueAtTime(.001,start);g.gain.exponentialRampToValueAtTime(.13,start+.015);g.gain.exponentialRampToValueAtTime(.001,start+.2);o.start(start);o.stop(start+.22)})}
function enableAudio(){try{audio||=new AudioContext();audio.resume()}catch{$('#settings-error').textContent='Звук недоступен. Завершение появится на экране.'}}
function advance(now){const t=state.pomodoro;if(t.deadline===null)return 0;let count=0;while(t.deadline<=now&&count<100){const focus=t.phase==='focus';t.completed+=focus?1:0;t.phase=focus?(t.completed%settings.cycles===0?'long':'short'):'focus';t.remaining=duration(t.phase);t.notice=focus?'Сессия завершена. Время отдохнуть.':'Отдых завершён. Можно возвращаться к работе.';count++;t.deadline=settings.autoStart?t.deadline+duration(t.phase):null}if(t.deadline!==null)t.remaining=Math.max(0,t.deadline-now);return count}
function tabs(){document.querySelectorAll('[data-view]').forEach(tab=>{const active=tab.dataset.view===state.view;tab.setAttribute('aria-selected',active);tab.setAttribute('aria-current',active?'page':'false')});document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==state.view);$('#section-code').textContent=codes[state.view];$('[data-running="stopwatch"]').hidden=state.stopwatch.startedAt===null;$('[data-running="pomodoro"]').hidden=state.pomodoro.deadline===null}
function renderPomodoro(){const t=state.pomodoro,running=t.deadline!==null,total=duration(t.phase),progress=Math.min(100,Math.max(0,100*(1-t.remaining/total))),rem=countdown(t.remaining),done=t.completed%settings.cycles,visible=t.phase==='long'&&done===0&&t.completed>0?settings.cycles:done,session=t.phase==='focus'?done+1:done||settings.cycles;status($('#pomodoro-status'),running?'Идёт отсчёт':t.remaining<total?'На паузе':'Готов к старту',running);$('#pomodoro-heading').textContent=t.phase==='focus'?'Время сосредоточиться.':'Пауза тоже часть работы.';$('#pomodoro-digits').innerHTML=`${rem.split(':')[0]}<span>:</span>${rem.split(':')[1]}`;$('#pomodoro-digits').setAttribute('aria-label',`Осталось ${rem}`);$('#session-label').innerHTML=`СЕССИЯ ${pad(session)} <span>/ ${pad(settings.cycles)}</span>`;$('#pomodoro-toggle').innerHTML=`<span>${running?'Пауза':t.remaining<total?'Продолжить':t.phase==='focus'?'Начать фокус':'Начать отдых'}</span>`;$('#pomodoro-notice').textContent=t.notice;$('#progress-label').textContent=labels[t.phase];$('#progress-value').textContent=`${settings[t.phase]} мин · ${Math.floor(progress)}%`;$('#progress-indicator').style.width=`${progress}%`;$('#session-marks').setAttribute('aria-label',`Завершено в цикле: ${visible} из ${settings.cycles}`);$('#session-marks').innerHTML=Array.from({length:settings.cycles},(_,i)=>`<b class="${i<visible?'complete':''}"></b>`).join('');document.querySelectorAll('[data-phase]').forEach(b=>b.classList.toggle('selected',b.dataset.phase===t.phase));document.title=running?`${rem} · ${labels[t.phase]} — 6.am`:'6.am — Время'}
function renderClock(){const d=new Date(state.now),format24=$('#clock-format').checked;$('#clock-digits').textContent=d.toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:!format24});$('#date-label').textContent=d.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long',year:'numeric'});$('#time-zone').textContent=Intl.DateTimeFormat().resolvedOptions().timeZone.replaceAll('_',' ');$('#clock-rule').innerHTML=Array.from({length:60},(_,i)=>`<i class="${i<=d.getSeconds()?'elapsed':''}"></i>`).join('')}
function renderStopwatch(){const time=elapsed(state.stopwatch),running=state.stopwatch.startedAt!==null;status($('#stopwatch-status'),running?'Идёт отсчёт':time?'На паузе':'Готов к старту',running);$('#stopwatch-digits').innerHTML=`${elapsedText(time)}<small class="hundredths">.${pad(Math.floor(time%1000/10))}</small>`;$('#stopwatch-toggle').innerHTML=`<span>${running?'Пауза':time?'Продолжить':'Начать'}</span>`;$('#stopwatch-reset').disabled=time===0;$('#stopwatch-lap').disabled=!running||state.stopwatch.laps.length>=100;$('#laps-empty').hidden=state.stopwatch.laps.length>0;$('#laps').hidden=state.stopwatch.laps.length===0;$('#laps-body').innerHTML=state.stopwatch.laps.map((lap,i)=>{const prev=state.stopwatch.laps[i-1]||0;return `<tr><td>${pad(i+1)}</td><td>${elapsedText(lap-prev)}.${pad(Math.floor((lap-prev)%1000/10))}</td><td>${elapsedText(lap)}.${pad(Math.floor(lap%1000/10))}</td></tr>`}).reverse().join('')}
function render(){tabs();renderPomodoro();renderClock();renderStopwatch()}
document.querySelectorAll('[data-view]').forEach(tab=>tab.addEventListener('click',()=>{if(codes[tab.dataset.view]){state.view=tab.dataset.view;history.replaceState(null,'',`#${state.view}`);tabs()}}));window.addEventListener('hashchange',()=>{if(codes[location.hash.slice(1)]){state.view=location.hash.slice(1);tabs()}});
document.querySelectorAll('[data-phase]').forEach(b=>b.addEventListener('click',()=>{state.pomodoro.phase=b.dataset.phase;state.pomodoro.remaining=duration(state.pomodoro.phase);state.pomodoro.deadline=null;state.pomodoro.notice='';render()}));
$('#pomodoro-toggle').addEventListener('click',()=>{const now=Date.now();if(state.pomodoro.deadline!==null){state.pomodoro.remaining=Math.max(0,state.pomodoro.deadline-now);state.pomodoro.deadline=null}else{if(settings.sound)enableAudio();state.pomodoro.deadline=now+state.pomodoro.remaining;state.pomodoro.notice=''}render()});$('#pomodoro-reset').addEventListener('click',()=>{state.pomodoro.remaining=duration(state.pomodoro.phase);state.pomodoro.deadline=null;state.pomodoro.notice='';render()});
$('#stopwatch-toggle').addEventListener('click',()=>{if(state.stopwatch.startedAt!==null){state.stopwatch.accumulated=elapsed(state.stopwatch);state.stopwatch.startedAt=null}else{state.stopwatch.startedAt=Date.now();startStopwatchFrame()}render()});$('#stopwatch-reset').addEventListener('click',()=>{state.stopwatch={accumulated:0,startedAt:null,laps:[]};render()});$('#stopwatch-lap').addEventListener('click',()=>{if(state.stopwatch.startedAt!==null&&state.stopwatch.laps.length<100){state.stopwatch.laps.push(elapsed(state.stopwatch));renderStopwatch()}});$('#clock-format').addEventListener('change',renderClock);
$('#settings-form').addEventListener('submit',event=>{event.preventDefault();const next={focus:Number($('#focus-input').value),short:Number($('#short-input').value),long:Number($('#long-input').value),cycles:Number($('#cycles-input').value),sound:$('#sound-input').checked,autoStart:$('#auto-start-input').checked};$('#settings-error').textContent='';if(!valid(next)){ $('#settings-error').textContent='Укажи целые минуты от 1 до 180 и число сессий от 1 до 12.';return}settings=next;state.pomodoro={phase:'focus',remaining:duration('focus'),deadline:null,completed:0,notice:''};try{localStorage.setItem('6am-preferences',JSON.stringify(settings))}catch{}$('#settings-feedback').textContent='Настройки сохранены на этом устройстве.';render()});
[['focus','focus-input'],['short','short-input'],['long','long-input'],['cycles','cycles-input']].forEach(([key,id])=>{$('#'+id).value=settings[key]});$('#sound-input').checked=settings.sound;$('#auto-start-input').checked=settings.autoStart;document.addEventListener('visibilitychange',()=>{state.now=Date.now();const n=advance(state.now);if(n&&settings.sound)sound();render();if(state.stopwatch.startedAt!==null)startStopwatchFrame()});setInterval(()=>{state.now=Date.now();const n=advance(state.now);if(n&&settings.sound)sound();tabs();renderPomodoro();renderClock()},250);render();
